import React, { useState } from 'react';
import { Network, Terminal, CheckCircle2, AlertTriangle, Code, Play, Zap, Activity, Upload } from 'lucide-react';
import { registerCustomAlgo, benchmarkCustomAlgo } from '../api/client';

const DEFAULT_PLUGIN_CODE = `# Bring Your Own Algorithm (BYOA) Plugin
# Write your custom encryption block-cipher below!

def encrypt(key: bytes, plaintext: bytes) -> bytes:
    # Example Custom Cipher: 
    # A simple XOR with the Kyber-derived master key
    key_cycle = (key * (len(plaintext) // len(key) + 1))[:len(plaintext)]
    return bytes(a ^ b for a, b in zip(plaintext, key_cycle))

def decrypt(key: bytes, ciphertext: bytes) -> bytes:
    # Since XOR is symmetric, decrypt is identical to encrypt
    key_cycle = (key * (len(ciphertext) // len(key) + 1))[:len(ciphertext)]
    return bytes(a ^ b for a, b in zip(ciphertext, key_cycle))
`;

export default function CustomAlgorithm() {
  const [code, setCode] = useState(DEFAULT_PLUGIN_CODE);
  const [isCompiling, setIsCompiling] = useState(false);
  const [status, setStatus] = useState<{ type: 'success' | 'error'; message: string } | null>(null);
  const [isBenchmarking, setIsBenchmarking] = useState(false);
  const [benchResults, setBenchResults] = useState<any | null>(null);
  const handleRegister = async () => {
    setIsCompiling(true);
    setStatus(null);
    setBenchResults(null);
    try {
      const res = await registerCustomAlgo(code);
      if (res.success) {
        setStatus({ type: 'success', message: res.message });
      }
    } catch (err: any) {
      setStatus({ type: 'error', message: err.response?.data?.detail || err.message || 'Compilation Failed' });
    } finally {
      setIsCompiling(false);
    }
  };

  const handleBenchmark = async () => {
    setIsBenchmarking(true);
    try {
      const res = await benchmarkCustomAlgo();
      if (res.success) setBenchResults(res);
    } catch (err: any) {
      setStatus({ type: 'error', message: err.response?.data?.detail || err.message || 'Benchmark Failed' });
    } finally {
      setIsBenchmarking(false);
    }
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (e) => {
      const content = e.target?.result as string;
      setCode(content);
      setStatus(null);
      setBenchResults(null);
    };
    reader.readAsText(file);
    // Reset the input so the same file could be selected again if needed
    e.target.value = '';
  };

  const lines = code.split('\n');

  return (
    <div className="page animate-fade-in">
      <div style={{ maxWidth: '1200px', margin: '0 auto', padding: '0 2.5rem 5rem' }}>

        {/* ── Header ── */}
        <header style={{ textAlign: 'center', paddingBottom: '2.5rem', paddingTop: '1rem' }}>
          <div style={{
            display: 'inline-flex', alignItems: 'center', gap: '0.5rem',
            background: 'rgba(0,229,255,0.08)', color: 'var(--cyan)',
            padding: '0.5rem 1.25rem', borderRadius: '999px',
            border: '1px solid rgba(0,229,255,0.2)', marginBottom: '1.25rem',
            fontSize: '0.7rem', fontFamily: 'var(--font-mono)',
            letterSpacing: '0.1em', textTransform: 'uppercase'
          }}>
            <Network style={{ width: 14, height: 14 }} />
            Bring Your Own Algorithm (BYOA)
          </div>
          <h1 style={{ fontSize: '3rem', fontWeight: 800, marginBottom: '0.75rem', lineHeight: 1.1 }}>
            Custom <span style={{ color: 'var(--cyan)' }}>Encryption</span> Plugin
          </h1>
          <p style={{ color: 'var(--text-muted)', maxWidth: '640px', margin: '0 auto', lineHeight: 1.7 }}>
            Inject your own Python encryption logic directly into the PQC pipeline. The master hybrid keys generated by CRYSTALS-Kyber and McEliece will automatically be supplied to your custom symmetric functions.
          </p>
        </header>

        {/* ── Editor Card ── */}
        <div style={{
          background: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.08)',
          borderRadius: '20px', backdropFilter: 'blur(16px)', overflow: 'hidden'
        }}>
          {/* Editor Header */}
          <div style={{
            display: 'flex', alignItems: 'center', justifyContent: 'space-between',
            padding: '1rem 1.5rem',
            borderBottom: '1px solid rgba(255,255,255,0.06)',
            background: 'rgba(0,0,0,0.2)'
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
              {/* Traffic lights */}
              <div style={{ display: 'flex', gap: '6px' }}>
                <div style={{ width: 12, height: 12, borderRadius: '50%', background: '#ff5f57' }} />
                <div style={{ width: 12, height: 12, borderRadius: '50%', background: '#febc2e' }} />
                <div style={{ width: 12, height: 12, borderRadius: '50%', background: '#28c840' }} />
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', fontFamily: 'var(--font-mono)', fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                <Code style={{ width: 14, height: 14, color: 'var(--cyan)' }} />
                live-backend-compiler.py
              </div>
              <div style={{ width: 1, height: 16, background: 'rgba(255,255,255,0.1)', margin: '0 0.5rem' }} />
              <label style={{
                display: 'flex', alignItems: 'center', gap: '0.35rem', cursor: 'pointer',
                fontFamily: 'var(--font-mono)', fontSize: '0.7rem', color: '#a78bfa',
                background: 'rgba(168,85,247,0.1)', padding: '0.2rem 0.6rem', borderRadius: '6px',
                border: '1px solid rgba(168,85,247,0.3)', transition: 'all 0.2s', fontWeight: 600
              }}>
                <Upload style={{ width: 12, height: 12 }} /> Upload .py File
                <input type="file" accept=".py,.txt" onChange={handleFileUpload} style={{ display: 'none' }} />
              </label>
            </div>
            {status && (
              <div style={{
                display: 'flex', alignItems: 'center', gap: '0.4rem',
                padding: '0.35rem 0.85rem', borderRadius: '8px',
                fontFamily: 'var(--font-mono)', fontSize: '0.72rem',
                background: status.type === 'success' ? 'rgba(0,255,136,0.1)' : 'rgba(239,68,68,0.1)',
                color: status.type === 'success' ? 'var(--green)' : '#f87171',
                border: `1px solid ${status.type === 'success' ? 'rgba(0,255,136,0.2)' : 'rgba(239,68,68,0.2)'}`
              }}>
                {status.type === 'success'
                  ? <CheckCircle2 style={{ width: 13, height: 13 }} />
                  : <AlertTriangle style={{ width: 13, height: 13 }} />}
                {status.message}
              </div>
            )}
          </div>

          {/* Code Editor */}
          <div style={{
            display: 'flex', background: '#0d1117',
            minHeight: '420px', fontFamily: 'var(--font-mono)', fontSize: '0.82rem'
          }}>
            {/* Line numbers */}
            <div style={{
              width: '3.5rem', padding: '1.25rem 0.75rem 1.25rem 0',
              background: '#0d1117', borderRight: '1px solid rgba(255,255,255,0.05)',
              color: 'rgba(255,255,255,0.15)', textAlign: 'right',
              userSelect: 'none', lineHeight: '1.6', flexShrink: 0
            }}>
              {lines.map((_, i) => (
                <div key={i}>{i + 1}</div>
              ))}
            </div>
            {/* Textarea */}
            <textarea
              value={code}
              onChange={(e) => setCode(e.target.value)}
              spellCheck={false}
              style={{
                flex: 1, background: 'transparent', border: 'none', outline: 'none',
                color: '#7ee787', padding: '1.25rem 1.25rem',
                lineHeight: '1.6', resize: 'none', fontFamily: 'inherit',
                fontSize: 'inherit', minHeight: '420px'
              }}
            />
          </div>

          {/* Footer / Deploy bar */}
          <div style={{
            display: 'flex', alignItems: 'center', justifyContent: 'space-between',
            padding: '1rem 1.5rem', flexWrap: 'wrap', gap: '1rem',
            borderTop: '1px solid rgba(255,255,255,0.06)',
            background: 'rgba(0,0,0,0.25)'
          }}>
            <div style={{ display: 'flex', alignItems: 'flex-start', gap: '0.6rem', maxWidth: '600px' }}>
              <AlertTriangle style={{ width: 14, height: 14, color: 'var(--amber)', marginTop: 2, flexShrink: 0 }} />
              <p style={{ fontFamily: 'var(--font-mono)', fontSize: '0.72rem', color: 'var(--text-muted)', lineHeight: 1.5 }}>
                Deploying an algorithm executes a live hot-reload on the FastAPI layer.
                Once successfully compiled, toggle it ON within the Secure Chat interface.
              </p>
            </div>
            <div style={{ display: 'flex', gap: '0.75rem' }}>
              {status?.type === 'success' && (
                <button
                  onClick={handleBenchmark}
                  disabled={isBenchmarking}
                  style={{
                    display: 'flex', alignItems: 'center', gap: '0.5rem',
                    padding: '0.65rem 1.25rem', borderRadius: '10px',
                    background: isBenchmarking ? 'rgba(168,85,247,0.1)' : 'rgba(168,85,247,0.15)',
                    color: '#c084fc', border: '1px solid rgba(168,85,247,0.3)',
                    fontFamily: 'var(--font-mono)', fontSize: '0.82rem', fontWeight: 600,
                    cursor: isBenchmarking ? 'not-allowed' : 'pointer',
                    transition: 'all 0.2s', letterSpacing: '0.03em',
                  }}
                >
                  {isBenchmarking
                    ? <><div style={{ width: 14, height: 14, border: '2px solid rgba(168,85,247,0.3)', borderTopColor: '#c084fc', borderRadius: '50%', animation: 'spin 0.8s linear infinite' }} /> Profiling...</>
                    : <><Activity style={{ width: 14, height: 14 }} /> Run Benchmark</>
                  }
                </button>
              )}
              <button
                onClick={handleRegister}
                disabled={isCompiling}
                style={{
                  display: 'flex', alignItems: 'center', gap: '0.5rem',
                  padding: '0.65rem 1.75rem', borderRadius: '10px',
                  background: isCompiling ? 'rgba(0,229,255,0.08)' : 'rgba(0,229,255,0.12)',
                  color: 'var(--cyan)', border: '1px solid rgba(0,229,255,0.3)',
                  fontFamily: 'var(--font-mono)', fontSize: '0.82rem', fontWeight: 700,
                  cursor: isCompiling ? 'not-allowed' : 'pointer',
                  transition: 'all 0.2s', letterSpacing: '0.03em',
                  boxShadow: isCompiling ? 'none' : '0 0 16px rgba(0,229,255,0.1)'
                }}
              >
                {isCompiling
                  ? <><div style={{ width: 14, height: 14, border: '2px solid rgba(0,229,255,0.2)', borderTopColor: 'var(--cyan)', borderRadius: '50%', animation: 'spin 0.8s linear infinite' }} /> Compiling...</>
                  : <><Play style={{ width: 14, height: 14 }} /> Hot-Reload Plugin</>
                }
              </button>
            </div>
          </div>
        </div>

        {/* ── Post-deploy Metrics ── */}
        {status?.type === 'success' && (
          <div style={{ display: 'grid', gridTemplateColumns: '1fr', gap: '1.5rem', marginTop: '1.5rem' }} className="animate-fade-in">
            {/* CTA before benchResults exist */}
            {!benchResults && (
              <div style={{
                background: 'rgba(168,85,247,0.05)', border: '1px dashed rgba(168,85,247,0.3)',
                borderRadius: '16px', padding: '3rem 2rem', textAlign: 'center'
              }}>
                <Zap style={{ width: 32, height: 32, color: '#a855f7', margin: '0 auto 1rem', opacity: 0.8 }} />
                <h3 style={{ fontFamily: 'var(--font-mono)', fontSize: '1.25rem', color: '#c084fc', marginBottom: '0.5rem' }}>Plugin Active In-Memory</h3>
                <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem', maxWidth: '500px', margin: '0 auto' }}>
                  Your algorithm has been successfully compiled. To generate an honest, computationally-backed cryptographic threat report, run the Benchmark Profiler above to launch the runtime evaluation engine.
                </p>
              </div>
            )}

            {/* Post-Benchmark Detailed Scientific Threat Report */}
            {benchResults && benchResults.evaluation && (
              <div style={{ background: 'rgba(0,0,0,0.3)', border: '1px solid rgba(255,255,255,0.08)', borderRadius: '16px', padding: '2rem' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}>
                  <h3 style={{ fontSize: '1.1rem', fontFamily: 'var(--font-mono)', display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--text-primary)' }}>
                    <Activity style={{ color: 'var(--cyan)' }} /> 
                    Runtime Cryptographic Analysis
                  </h3>
                  <span style={{ 
                    fontFamily: 'var(--font-mono)', fontSize: '0.8rem', fontWeight: 600, padding: '0.3rem 0.8rem', borderRadius: '4px',
                    background: benchResults.evaluation.final_score.startsWith('10') ? 'rgba(0,255,136,0.1)' : 'rgba(239,68,68,0.1)',
                    color: benchResults.evaluation.final_score.startsWith('10') ? 'var(--green)' : '#ef4444'
                  }}>
                    Engine Score: {benchResults.evaluation.final_score}
                  </span>
                </div>
                
                {/* Strict Rule 6: Not Secure For Real Use */}
                {(parseInt(benchResults.evaluation.final_score.split('/')[0]) < 7 || benchResults.evaluation.shor === 'VULNERABLE') && (
                  <div style={{ background: 'rgba(239,68,68,0.08)', border: '1px solid rgba(239,68,68,0.3)', color: '#f87171', padding: '1rem', borderRadius: '8px', marginBottom: '2rem', fontFamily: 'var(--font-mono)', fontWeight: 800, textAlign: 'center', letterSpacing: '0.05em' }}>
                    ⚠️ NOT SECURE FOR REAL USE ⚠️
                  </div>
                )}

                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '1rem' }}>
                  {/* Shor */}
                  <div style={{ background: 'rgba(255,255,255,0.02)', padding: '1.25rem', borderRadius: '8px', border: '1px solid rgba(255,255,255,0.05)' }}>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.65rem', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '0.5rem' }}>Shor's Resiliency</div>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.9rem', fontWeight: 600, color: benchResults.evaluation.shor.includes('VULNERABLE') ? '#f87171' : 'var(--green)', marginBottom: '0.3rem' }}>
                      {benchResults.evaluation.shor}
                    </div>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.65rem', color: 'var(--text-muted)', lineHeight: 1.4 }}>
                      {benchResults.evaluation.shor.includes('VULNERABLE') 
                        ? "✗ Broken by quantum period-finding (Hidden Subgroup Problem)." 
                        : "✓ No known polynomial-time quantum attack exists."}
                    </div>
                  </div>
                  
                  {/* Grover */}
                  <div style={{ background: 'rgba(255,255,255,0.02)', padding: '1.25rem', borderRadius: '8px', border: '1px solid rgba(255,255,255,0.05)' }}>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.65rem', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '0.5rem' }}>Grover's Impact Limit</div>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.9rem', fontWeight: 600, color: 'var(--amber)', marginBottom: '0.3rem' }}>
                      {benchResults.evaluation.grover}
                    </div>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.65rem', color: 'var(--text-muted)', lineHeight: 1.4 }}>
                      ⚠ Quantum search requires O(√N) amplitude amplification operations.
                    </div>
                  </div>
                  
                  {/* Classical */}
                  <div style={{ background: 'rgba(255,255,255,0.02)', padding: '1.25rem', borderRadius: '8px', border: '1px solid rgba(255,255,255,0.05)' }}>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.65rem', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '0.5rem' }}>Classical Security Heuristic</div>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.9rem', fontWeight: 600, color: benchResults.evaluation.classical_strength === 'STRONG' ? 'var(--green)' : benchResults.evaluation.classical_strength === 'MODERATE' ? 'var(--amber)' : '#f87171', marginBottom: '0.3rem' }}>
                      {benchResults.evaluation.classical_strength}
                    </div>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.65rem', color: 'var(--text-muted)', lineHeight: 1.4 }}>
                      {benchResults.evaluation.classical_strength.includes('WEAK')
                        ? "✗ Vulnerable to differential/linear cryptanalysis."
                        : "✓ Structurally resistant to known classical attacks."}
                    </div>
                  </div>
                  
                  {/* Harvest */}
                  <div style={{ background: 'rgba(255,255,255,0.02)', padding: '1.25rem', borderRadius: '8px', border: '1px solid rgba(255,255,255,0.05)' }}>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.65rem', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '0.5rem' }}>Harvest-Now-Decrypt-Later</div>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.9rem', fontWeight: 600, color: benchResults.evaluation.harvest_attack === 'SAFE' ? 'var(--green)' : '#f87171', marginBottom: '0.3rem' }}>
                      {benchResults.evaluation.harvest_attack}
                    </div>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.65rem', color: 'var(--text-muted)', lineHeight: 1.4 }}>
                      {benchResults.evaluation.harvest_attack === 'SAFE'
                        ? "✓ Perfect Forward Secrecy secures against future quantum decryption."
                        : "✗ High-value target for State-Backed SNDL data harvesting."}
                    </div>
                  </div>
                  
                  {/* Avalanche */}
                  <div style={{ background: 'rgba(255,255,255,0.02)', padding: '1.25rem', borderRadius: '8px', border: '1px solid rgba(255,255,255,0.05)' }}>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.65rem', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '0.5rem' }}>Avalanche Property (1-bit shift)</div>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: '1.1rem', fontWeight: 700, color: '#c084fc', marginBottom: '0.3rem' }}>
                      {benchResults.evaluation.avalanche_score}
                    </div>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.65rem', color: 'var(--text-muted)', lineHeight: 1.4 }}>
                      {parseFloat(benchResults.evaluation.avalanche_score) < 30 
                        ? "✗ Critical: Low avalanche → poor diffusion (bits do not scramble)." 
                        : "✓ Strong diffusion (strict avalanche criterion met by non-linear layers)."}
                    </div>
                  </div>
                  
                  {/* Entropy */}
                  <div style={{ background: 'rgba(255,255,255,0.02)', padding: '1.25rem', borderRadius: '8px', border: '1px solid rgba(255,255,255,0.05)' }}>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.65rem', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '0.5rem' }}>Shannon Entropy (Ciphertext)</div>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: '1.1rem', fontWeight: 700, color: '#c084fc', marginBottom: '0.3rem' }}>
                      {benchResults.evaluation.entropy}
                    </div>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.65rem', color: 'var(--text-muted)', lineHeight: 1.4 }}>
                      {parseFloat(benchResults.evaluation.entropy.split(' ')[0]) < 7.5
                        ? "✗ Critical: Low entropy → predictable output (patterns exist)."
                        : "✓ High pseudorandomness (ciphertext is indistinguishable from noise)."}
                    </div>
                  </div>

                  {/* Brute Force Summary */}
                  <div style={{ gridColumn: '1 / -1', background: 'rgba(0,0,0,0.2)', padding: '1rem 1.25rem', borderRadius: '8px', border: '1px solid rgba(255,255,255,0.03)', display: 'flex', gap: '2rem' }}>
                    <div>
                      <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.65rem', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '0.25rem' }}>Classical Brute Force Limit</div>
                      <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.85rem', color: 'var(--text-primary)' }}>{benchResults.evaluation.bruteforce.classical} attempts</div>
                    </div>
                    <div>
                      <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.65rem', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '0.25rem' }}>Quantum Search Limit</div>
                      <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.85rem', color: 'var(--text-primary)' }}>{benchResults.evaluation.bruteforce.quantum} attempts</div>
                    </div>
                  </div>
                </div>
              </div>
            )}

            {/* Benchmark Results Table (spans full width) */}
            {benchResults && (
              <div style={{ gridColumn: '1 / -1', background: 'rgba(0,0,0,0.3)', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '16px', padding: '1.5rem', overflow: 'hidden' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.25rem' }}>
                  <h3 style={{ fontFamily: 'var(--font-mono)', fontSize: '1rem', color: 'var(--text-primary)', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                    <Activity style={{ width: 16, height: 16, color: 'var(--cyan)' }} />
                    Performance vs AES-256-GCM
                  </h3>
                  <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.75rem', color: benchResults.overall_correct ? 'var(--green)' : '#f87171', display: 'flex', alignItems: 'center', gap: '0.4rem', border: `1px solid ${benchResults.overall_correct ? 'rgba(0,255,136,0.3)' : 'rgba(239,68,68,0.3)'}`, padding: '0.25rem 0.75rem', borderRadius: '999px' }}>
                    {benchResults.overall_correct ? <CheckCircle2 style={{ width: 14, height: 14 }} /> : <AlertTriangle style={{ width: 14, height: 14 }} />}
                    {benchResults.overall_correct ? 'Cipher Correctness: PASSED' : 'Cipher Correctness: FAILED'}
                  </div>
                </div>

                <div style={{ overflowX: 'auto' }}>
                  <table style={{ width: '100%', borderCollapse: 'collapse', fontFamily: 'var(--font-mono)', fontSize: '0.8rem', textAlign: 'left' }}>
                    <thead>
                      <tr style={{ borderBottom: '1px solid rgba(255,255,255,0.1)', color: 'var(--text-muted)' }}>
                        <th style={{ padding: '0.75rem 1rem', fontWeight: 600 }}>Payload</th>
                        <th style={{ padding: '0.75rem 1rem', fontWeight: 600 }}>Encrypt</th>
                        <th style={{ padding: '0.75rem 1rem', fontWeight: 600 }}>Decrypt</th>
                        <th style={{ padding: '0.75rem 1rem', fontWeight: 600 }}>Throughput</th>
                        <th style={{ padding: '0.75rem 1rem', fontWeight: 600 }}>vs AES Encrypt</th>
                      </tr>
                    </thead>
                    <tbody>
                      {benchResults.results.map((r: any, i: number) => (
                        <tr key={i} style={{ borderBottom: '1px solid rgba(255,255,255,0.05)' }}>
                          <td style={{ padding: '0.75rem 1rem', color: 'var(--cyan)' }}>{r.payload_label}</td>
                          <td style={{ padding: '0.75rem 1rem' }}>{r.encrypt_ms} ms</td>
                          <td style={{ padding: '0.75rem 1rem' }}>{r.decrypt_ms} ms</td>
                          <td style={{ padding: '0.75rem 1rem', color: '#c084fc' }}>{r.throughput_mbps} MB/s</td>
                          <td style={{ padding: '0.75rem 1rem' }}>
                            <span style={{ color: r.vs_aes.encrypt_ratio <= 1.2 ? 'var(--green)' : r.vs_aes.encrypt_ratio > 5 ? '#f87171' : 'var(--amber)' }}>
                              {r.vs_aes.encrypt_ratio}x {r.vs_aes.encrypt_ratio <= 1 ? 'faster' : 'slower'}
                            </span>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
